name: Publish Events

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  workflow_dispatch:  # Allow manual triggers

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account JSON
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/sa.json" >> $GITHUB_ENV
          
      - name: Verify environment
        run: |
          echo "Python version:"
          python --version
          echo "Pip version:"
          pip --version
          echo "Working directory:"
          pwd
          echo "Service account file exists:"
          test -f "$GOOGLE_APPLICATION_CREDENTIALS" && echo "Yes" || echo "No"
          echo "Environment variables set:"
          env | grep -E "GCAL_ID|GOOGLE_APPLICATION|REDDIT_"
          
      - name: Run event aggregator
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          GCAL_ID: ${{ secrets.GCAL_ID }}
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "Starting event aggregator..."
          python -m src.main
        continue-on-error: true
        
      - name: Send failure notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          secure: true
          subject: "MTL Events Agent FAILED"
          to: tzachpach@gmail.com
          from: mtl-events-agent
          body: "See GitHub Actions log for details." 